UI kit example
AlexRzhk/admin-panel pull request #2
Opened 2022-08-19 12:58 UTC by AlexRzhk

https://alexrzhk.github.io/admin-panel/

2022-08-19 13:00 UTC, AlexRzhk commented
https://alexrzhk.github.io/admin-panel/

2022-08-23 22:31 UTC, Muslik requested changes
- КЛАССЫ НЕ ПО БЭМ. НЕ МОЖЕТ БЫТЬ Модификатора без блока. Старайтесь разделять модификаторы вида blue_wide на _color_blue и _size_wide. Маленькие модификаторы легче контроллировать и менять.
- Проверьте свою работу на предмет сходства с макетом. Много различий.
- Не работают checkbox, radio в dropdown
- input с замочком - disabled. Не может туда ставиться фокус.
- Обводка при фокусе input-а должна стать на весь input а не только на внутреннюю часть.
- Будет хорошо если вы как то скомпонуете блоки ближе друг к другу.
- В dropdown переиспользуйте которые вы сделали раньше.

2022-08-23 22:31 UTC, Muslik commented on ui-kit/ui.html
> +        <button class="button-full__area_black-wide">
Хотелось бы чтобы вы разделили модификаторы:
```css
.button {} // Тут основные стили

.button_color_black {} // Тут цвета
.button_size_big {} // Тут размер
```
В вашем случае при добавлении нового цвета, нужно будет добавлять два класса. (```button-full__area_black-wide``` и ```button-full__area_blue-wide```

2022-08-23 22:31 UTC, Muslik commented on ui-kit/ui.html
> +            <svg class="button__img_black-wide" viewBox="0 0 16 16" fill="none" stroke="#FFFFFF" xmlns="http://www.w3.org/2000/svg">
Не нужно у иконок дублировать модификаторы.
```css
.button_color_black .button__img {}
```

2022-08-23 22:31 UTC, Muslik commented on ui-kit/ui.html
> +        <button class="button__area_black-wide">
button должен быть самостоятельным блоком. (Класс по БЭМ должен быть просто ```.button```)

2022-08-23 22:31 UTC, Muslik commented on ui-kit/ui.html
> +            <button class="dropdown-delete__button_delete">
Переиспользуем кнопки которые делали ранее

2022-08-23 22:31 UTC, Muslik commented on ui-kit/ui.html
> +            <button class="dropdown-status-multiple__button_active">
Это не button. Это label и текст. Обернуть можно div-ом

2022-08-23 22:31 UTC, Muslik commented on ui-kit/ui.html
> +            <button class="dropdown-status-single__button_inactive">Новый</button>
Это radio. И работать должны как radio.

2022-08-23 22:31 UTC, Muslik commented on ui-kit/ui.html
> +            <button class="dropdown-status-multiple__button_active">
У dropdown-а может быть только padding сверху и снизу. Сам checkbox вместе с его label должен тянуться на всю ширину. По клику на текст чекбокс должен включаться. То же относится и к radio

2022-08-23 22:31 UTC, Muslik commented on ui-kit/ui.html
> +        <div class = 'input-area_wrapper_locked'>
Этот модификатор locker должен быть у родительского элемента. Как с button

2022-08-23 22:31 UTC, Muslik commented on ui-kit/ui.html
> +            <button class = 'button_locked' onclick="alert('smth')">
не может быть модификатор без блока.

2022-08-27 21:58 UTC, Muslik requested changes
Прикреплю видео

2022-08-27 21:58 UTC, Muslik commented on css/dropdown.css
> +.button_dropdown{
Этот класс должен быть .dropdown__button если на то пошло.
Потому что модификаторы для самой кнопки должны быть рядом с кнопкой.

А во вторых я бы вынес это в модификатор ```.button_full-width`` и положил бы к кнопке. И там бы уже указал width: 100%. Потому что сейчас у вас кнопка тянется не на всю ширину а на заранее указанную (8rem)

2022-08-27 21:58 UTC, Muslik commented on ui-kit/css/ui.css
> +    min-width: 3.5rem;
Зачем это? Кнопка сама занимает место по контенту

2022-08-27 21:58 UTC, Muslik commented on ui-kit/css/ui.css
> +.button-full_small{
У вас padding-и совпадают с классом ниже. А это значит что из надо обьединить. Положите их в классы с размером. Сейчас у вас получается есть ```.button_small```, ```.button-img_small```, ```.button__text_small```. Через чур много классов в которых нет необходимости.

У кнопки должно быть три модификатора: ```_color_...```, ```_size_...```, ```_icon-only```
Больше ничего не нужно.
Если вам нужно указать размер текста в зависимости от размера кнопки:
```.button_size_medium .button__text```

2022-08-27 21:58 UTC, Muslik commented on ui-kit/css/ui.css
> +.button-full_small{
А то сейчас при добавлении допустим размера ```extra-large``` вам нужно будет столько классов продублировать

2022-08-30 13:48 UTC, AlexRzhk commented
https://alexrzhk.github.io/admin-panel/
в последнем коммите - переименовал класс и добавил стилей тексту, основные изменения в коммите [54d793a](https://github.com/AlexRzhk/admin-panel/pull/2/commits/54d793a14e4a68fc0709d1ed79ad3a72a148a643)

2022-08-31 01:19 UTC, Muslik approved these changes
Есть небольшие замечания.

2022-08-31 01:19 UTC, Muslik commented on css/checkbox.css
> +:root{
Шрифт у вас по прежнему не 'Ubuntu'

2022-08-31 01:19 UTC, Muslik commented on index.html
> +                        <input class="input-area input-area_danger input__text" id="date-input_danger" type="text" value="06.12.2021" placeholder="Введите"/>
Очень странно что у вас input__text и тут и выше у другого блока. Хотя это по смыслу разные блоки.

2022-08-31 01:19 UTC, Muslik commented on index.html
> +    <div class="dropdown_block">
Не может быть модификатора без основного класса

2022-08-31 01:19 UTC, Muslik commented on ui-kit/ui.html
> +                    <input class="search__input search__text" type="text" placeholder="Номер заказа или ФИО"/>
Один класс какой то выберите. Либо .search__input, либо .search__text :)

2022-09-05 09:29 UTC, merged